// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Head: typeof import('@vueuse/head')['Head']
    Island: typeof import('iles')['Island']
    Test: typeof import('./src/components/Test.vue')['default']
    Test2: typeof import('./src/components/Test2.vue')['default']
  }
}

export { }
